angular.module("themeConfig", [])
.constant("pool", "_poolBear")
.constant("playerFilter", [{"filterId":1,"filterName":"PLATFORM"},{"filterId":2,"filterName":"PLAYED"}])
.constant("sortFilter", [{"sortId":1,"filterName":"elo"},{"sortId":2,"filterName":"wins"},{"sortId":3,"filterName":"lost"}])
.constant("languageID", " 221")
.constant("languageCode", "en")
.constant("deployPath", "/Volumes/Macintosh HD 2/dev/microsoft-staging/BearDeploy/")
.constant("deployDist", "/Volumes/Macintosh HD 2/dev/The-Bear/dist/")
.constant("themeData", ["'poolBear'","'footballBear'","'SquashBear'","'golfBear'","'cSBear'","'tennisBear'"])
.constant("ratingSystem", {"standard":"_standard","advanced":"_advanced","custom":"_custom"})
.constant("app", ["'firebase'","'ui.router'","'poolBear.login'","'poolBear.auth'","'poolBear.result'","'poolBear.settings'","'poolBear.actionmodal'","'poolBear.scoreMessage'","'poolBear.Message'","'poolBear.uploadFile'","'poolBear.Images'","'poolBear.Images'","'poolBear.uploadFileService'","'poolBear.search'","'poolBear.challenge'","'poolBear.group'","'poolBear.geo'","'poolBear.bio'","'poolBear.chat'","'poolBear.api'","'poolbear.confirmServices'","'themeConfig'","'services.menu'","'slickCarousel'","'slickExampleApp'"]);
